# Generated by Django 2.2 on 2019-12-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='manufacturing_date',
            field=models.DateTimeField(),
        ),
    ]
