# Generated by Django 2.2 on 2019-12-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0003_auto_20191201_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='distance_achievement_date',
            field=models.DateField(),
        ),
    ]
