# Generated by Django 2.2 on 2019-12-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0004_auto_20191201_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='inserted_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
