# Generated by Django 2.2 on 2019-12-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0005_auto_20191201_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='piolt',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
