# Generated by Django 2.2 on 2019-12-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0006_auto_20191202_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='manufacturing_date',
            field=models.DateField(),
        ),
    ]
