# Generated by Django 2.2 on 2019-12-03 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0013_auto_20191203_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drones', to=settings.AUTH_USER_MODEL),
        ),
    ]
