# Generated by Django 2.2 on 2019-11-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='toy',
            name='release_date',
            field=models.DateTimeField(auto_now=True, verbose_name='release_date'),
        ),
    ]
